version: '3'

# Define services
services:

  # Cache service
  app:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on: 
      - redis 
    environment: 
      REDIS_URL: redis:6379    
    networks: 
      - backend

  # Redis Service   
  redis:
    image: "redis:alpine" 
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "6379:6379"

networks:
  backend:    


