# the port server will expose 
server:
    port: 3000

# this is overriden by REDIS_URL env set by docker but falls back to this if not set
redis:
    url: "redis:6379" 

# the final upstream target cache will route requests to
target:
    scheme: "https"
    url: "api.github.com"

    # GITHUB_API_TOKEN
    # TODO(@aniket.alshi) Remove this - antipattern to put secrets. 
    # Use flipr service to dynamically load secrets and config at runtime
    token: "a134f07a3624ba19c9bf38f461744e55dcb55d63"
    # timeout on tcp connection we want to impose
    timeout: 5 
