# the port server will expose 
server:
    port: 3000

# this is overriden by REDIS_URL env set by docker but falls back to this if not set
redis:
    url: "redis:6379"

# the final upstream target cache will route requests to
target:
    scheme: "https"
    url: "api.github.com"

    # API Token for upstream apis - is available from env variables
    token : ""

    # timeout on tcp connection we want to impose
    timeout: 5 

# configuration params about the cache
cache:
    refresh: 10 # refresh rate in seconds for refreshing the cache 

# all the params about org that need to go into url
org:
    name: &name Netflix
    
    # endpoints that we want to cache
    cached:
        - /
        - /orgs/*org_name
        - /orgs/*org_name/members
        - /orgs/*org_name/repos
