# the port server will expose 
server:
    port: 3000

# this is overriden by REDIS_URL env set by docker but falls back to this if not set
redis:
    url: "redis:6379" 

# the final upstream target cache will route requests to
target:
    scheme: "https"
    url: "api.github.com"

    # GITHUB_API_TOKEN
    # TODO(@aniket.alshi) Remove this - antipattern to put secrets. 
    # Use flipr service to dynamically load secrets and config at runtime
    token: "a04d46a68e73a054e363d9a9d7e2ff5ffa01eefe"
    # timeout on tcp connection we want to impose
    timeout: 5 
